query OwnedLinearIssueComments($issueId: ID!, $first: Int!, $after: String) {
  issues(filter: {id: {eq: $issueId}}, includeArchived: true, first: 2) {
    nodes {
    id team { id }
    comments(first: $first, after: $after, includeArchived: true, orderBy: createdAt) {
      nodes {
        id body url createdAt updatedAt archivedAt resolvedAt
        user { id name updatedAt }
        parent { id }
        issue { id identifier title url team { id name } project { id name } }
      }
      pageInfo { hasNextPage endCursor }
    }
    }
    pageInfo { hasNextPage endCursor }
  }
}
